# Generated by Django 2.2.2 on 2019-07-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('httpapitest', '0005_testcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='include',
            field=models.CharField(max_length=1024, null=True, verbose_name='前置config/test'),
        ),
    ]
