# Generated by Django 2.2.2 on 2019-08-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('httpapitest', '0009_testsuite'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodicTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('task', models.CharField(max_length=200)),
                ('crontab', models.CharField(max_length=200)),
                ('kwargs', models.TextField()),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '定时任务',
                'db_table': 'PeriodicTask',
            },
        ),
    ]
